#
# SC3020
# Docker Compose
# Postgres with TPC-H
#

version: '3.8'

services:
  postgres:
    image: ghcr.io/mrzzy/ntu-sc3020/project2_postgres_tpch:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

