name: "Project2 CI"
on:
  push:
    paths:
      - ".github/workflows/project_2.yaml"
      - "project2/**"
defaults:
  run:
    working-directory: project2
jobs:
  lint-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'
          cache: 'pip'

      - name: Install Dependencies
        run: 
          pip install -r requirements.txt

      - name: Lint Code
        run: |
          black --check .
          isort --check .
          ruff check

      - name: Run Tests
        run: pytest

